#!/usr/bin/env python3
"""Regenerate the pinned Python requirement files in requirements/ (maintainers only).

    python -m pip install uv        # once
    python scripts/update_locks.py  # then commit requirements/*.lock

The locks are *universal* (``uv pip compile --universal``): one file per purpose that
covers Windows, macOS and Linux through environment markers, with hashes. They pin
third-party packages only; photoband/captiontokens themselves are installed with
``pip install --no-deps -e .`` on top (scripts/bootstrap.py does both).

    requirements/app.lock    runtime dependencies
    requirements/dev.lock    runtime + [dev] (pytest, ruff, playwright, ...)
    requirements/build.lock  runtime + [build] (PyInstaller), used by packaging/*
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOCKS = {"app": [], "dev": ["dev"], "build": ["build"]}
PYTHON = "3.11"  # lowest supported; universal locks then resolve for all newer versions too


def main() -> int:
    uv = shutil.which("uv")
    if not uv:
        print("uv is not installed. Run: python -m pip install uv", file=sys.stderr)
        return 1
    os.makedirs(os.path.join(ROOT, "requirements"), exist_ok=True)
    for name, extras in LOCKS.items():
        out = os.path.join("requirements", f"{name}.lock")
        cmd = [uv, "pip", "compile", "pyproject.toml", "--universal", "--python-version", PYTHON,
               "--generate-hashes", "--quiet", "--no-header", "-o", out]
        for x in extras:
            cmd += ["--extra", x]
        if "--upgrade" in sys.argv:
            cmd.append("--upgrade")
        print("+", " ".join(cmd[1:]), flush=True)
        subprocess.run(cmd, cwd=ROOT, check=True)
        header = ("# Generated by scripts/update_locks.py (uv pip compile --universal). Do not edit.\n"
                  "# Install: python -m pip install -r " + out.replace(os.sep, "/") +
                  " && python -m pip install --no-deps -e .\n")
        p = os.path.join(ROOT, out)
        with open(p, encoding="utf-8") as fh:
            body = fh.read()
        with open(p, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(header + body)
    return 0


if __name__ == "__main__":
    sys.exit(main())
